---
title: "Exploring 515K European Hotel Reviews"
author: "Neil Kutty"
date: "9/16/2017"
output: 
    html_document:
        toc: true
---

## Load data and create derived variables

```{r  warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(fig.width=9, fig.height=8)
full = read.csv('Hotel_Reviews.csv')

library(dplyr)
library(tidyr)
library(ggplot2)
library(leaflet)
library(leaflet.extras)
library(grid)
library(gridExtra)
library(scales)
library(knitr)

# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
#Function to extract country from lat/lon (will be switching to getting name from address field)

# from:https://stackoverflow.com/a/14342127
library(sp)
library(rworldmap)

# The single argument to this function, points, is a data.frame in which:
#   - column 1 contains the longitude in degrees
#   - column 2 contains the latitude in degrees
coords2country = function(points)
{  
    countriesSP <- getMap(resolution='low')
    #countriesSP <- getMap(resolution='high') #you could use high res map from rworldxtra if you were concerned about detail
    
    # convert our list of points to a SpatialPoints object
    
    # pointsSP = SpatialPoints(points, proj4string=CRS(" +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))
    
    #setting CRS directly to that from rworldmap
    pointsSP = SpatialPoints(points, proj4string=CRS(proj4string(countriesSP)))  
    
    
    # use 'over' to get indices of the Polygons object containing each point 
    indices = over(pointsSP, countriesSP)
    
    # return the ADMIN names of each country
    indices$ADMIN  
    #indices$ISO3 # returns the ISO3 code 
    #indices$continent   # returns the continent (6 continent model)
    #indices$REGION   # returns the continent (7 continent model)
}
# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
```


```{r include=TRUE, eval=TRUE}
full$Review_Range = cut(full$Reviewer_Score, breaks=1.5:11, include.lowest=T)
full$lng[is.na(full$lng)] <- 0
full$lat[is.na(full$lat)] <- 0
full$Country = coords2country(cbind(full$lng, full$lat))
full$Total_Words = full$Review_Total_Negative_Word_Counts + full$Review_Total_Positive_Word_Counts
full$Positive_Word_Rate = full$Review_Total_Positive_Word_Counts/full$Total_Words

full$Review_Range = as.factor(cut(full$Reviewer_Score, breaks=1.5:11, include.lowest=T))
full$Review_Range = gsub(']',')',full$Review_Range)
full$Review_Range = factor(full$Review_Range, levels = c('(9.5,10.5)','(8.5,9.5)',
                                                         '(7.5,8.5)','(6.5,7.5)',
                                                         '(5.5,6.5)','(4.5,5.5)',
                                                         '(3.5,4.5)','(2.5,3.5)',
                                                         '[1.5,2.5)'))




```

## Group and Count

### Hotel Names
```{r message=FALSE, warning=FALSE}

#Get stats by unique hotel

hotel.names = full %>%
    select(Hotel_Name, Hotel_Address, lat, lng, Country, Average_Score, Total_Number_of_Reviews,
           Review_Total_Positive_Word_Counts, Review_Total_Negative_Word_Counts) %>%
    #Remove the 17 records without geo coordinates
    filter(lat != 0 & lng != 0) %>%
    group_by(Hotel_Name, Hotel_Address, lat, lng, Country,Average_Score, Total_Number_of_Reviews) %>%
    summarise(Tot_Pos_Words = sum(Review_Total_Positive_Word_Counts),
              Tot_Neg_Words = sum(Review_Total_Negative_Word_Counts),
              Total_Words = sum(Tot_Pos_Words + Tot_Neg_Words),
              Pos_Word_Rate = percent(Tot_Pos_Words/Total_Words),
              Neg_Word_Rate = percent(Tot_Neg_Words/Total_Words)) #%>%
    #use fx to get country from lat/lng
    #mutate(Country = coords2country(cbind(lng,lat)))

kable(head(as.data.frame(hotel.names)))
```

### Review Range
```{r message=FALSE, warning=FALSE}

review_range = full %>%
    select(Review_Range, Total_Number_of_Reviews,
           Review_Total_Positive_Word_Counts, Review_Total_Negative_Word_Counts, Hotel_Name) %>%
    # #Remove the 17 records without geo coordinates
    # filter(lat != 0 & lng != 0) %>%
    group_by(Review_Range) %>%
    summarise(Tot_Pos_Words = sum(Review_Total_Positive_Word_Counts),
              Tot_Neg_Words = sum(Review_Total_Negative_Word_Counts),
              Total_Words = sum(Tot_Pos_Words + Tot_Neg_Words),
              Pos_Word_Rate = percent(Tot_Pos_Words/Total_Words),
              Neg_Word_Rate = percent(Tot_Neg_Words/Total_Words),
              Num_Reviews = n(),
              Avg_Words_Per_Review = format(Total_Words/Num_Reviews,digits = 4)
    )

kable(as.data.frame(review_range))
```

### Country Stats
```{r message=FALSE, warning=FALSE}
#Get stats by country
country.stats = hotel.names %>%
    select(Country, Average_Score, Total_Number_of_Reviews, Tot_Pos_Words, Tot_Neg_Words,
           Total_Words) %>%
    group_by(Country) %>%
    summarize(Avg_Hotel_Review = mean(Average_Score),
              Positive_Words = sum(Tot_Pos_Words),
              Negative_Words = sum(Tot_Neg_Words),
              Total_Words = sum(Total_Words),
              Pos_Word_Rate = percent(Positive_Words/Total_Words),
              Neg_Word_Rate = percent(Negative_Words/Total_Words),
              Number_Hotels = n(),
              Total_Number_of_Reviews = sum(Total_Number_of_Reviews))
              
kable(as.data.frame(country.stats))
```

## Exploratory Charts

### By Review Score Range


```{r echo=FALSE}

p1 <- ggplot(review_range, aes(x=Review_Range,
                         y=Num_Reviews,
                         fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=review_range$Num_Reviews,nudge_y = 0.5)+
    ggtitle(label="Number of Reviews by Range of Score")+
    labs(xlab('Review Range'),ylab('Number of Reviews'))+
    theme(legend.position = 'off')

p2 <- ggplot(review_range, aes(x=Review_Range,
                               y=Pos_Word_Rate,
                               fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=review_range$Pos_Word_Rate,nudge_y = 0.2)+
    ggtitle(label="Percent Positive Words by Range of Score")+
    labs(xlab('Review Range'),ylab('Percent(%) Positive Words'))+
    theme(legend.position = 'bottom')

p3 <- ggplot(review_range, aes(x=Review_Range,
                               y=Avg_Words_Per_Review,
                               fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=review_range$Avg_Words_Per_Review,nudge_y = 0.2)+
    ggtitle(label="Average Words per Review by Range of Score")+
    labs(xlab('Review Range'),ylab('Avg. Words per Review'))+
    theme(legend.position = 'off')

g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g3 <- ggplotGrob(p3)

grid.draw(rbind(g1,g3, g2, size='last'))
```


### Only Negative by Review Score Range - Reviews Containing Only Negative Words

```{r echo=FALSE}
zero_positive <- filter(full, Review_Total_Positive_Word_Counts == 0 & Review_Total_Negative_Word_Counts > 0)

zero_pos_rng = zero_positive %>%
    select(Review_Range, Total_Number_of_Reviews, Review_Total_Negative_Word_Counts, Hotel_Name) %>%
    # #Remove the 17 records without geo coordinates
    # filter(lat != 0 & lng != 0) %>%
    group_by(Review_Range) %>%
    summarise(Total_Words = sum(Review_Total_Negative_Word_Counts),
              Num_Reviews = n(),
              Avg_Words_Per_Review = format(Total_Words/Num_Reviews,digits = 4)
              )


# -- -- -- -- -- -- -- -- -- --     >      >      >     >
p4 <- ggplot(zero_pos_rng, aes(x=Review_Range,
                               y=Num_Reviews,
                               fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=zero_pos_rng$Num_Reviews,nudge_y = 0.5)+
    ggtitle(label="Negative Words Only - Number of Reviews by Range of Score")+
    labs(xlab('Review Range'),ylab('Number of Reviews'))+
    scale_fill_brewer(palette = 'Set3')+
    theme(legend.position = 'off')

p5 <- ggplot(zero_pos_rng, aes(x=Review_Range,
                               y=Avg_Words_Per_Review,
                               fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=zero_pos_rng$Avg_Words_Per_Review,nudge_y = 0.2)+
    ggtitle(label="Negative Words Only - Average Words per Review by Range of Score")+
    labs(xlab('Review Range'),ylab('Avg. Words per Review'))+
    scale_fill_brewer(palette = 'Set3')+
    theme(legend.position = 'off')


p6 <- ggplot(zero_pos_rng, aes(x=Review_Range,
                               y=Total_Words,
                               fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=zero_pos_rng$Total_Words,nudge_y = 0.2)+
    ggtitle(label="Number of Negative Words by Range of Score")+
    labs(xlab('Review Range'),ylab('Number of Negative Words'))+
    scale_fill_brewer(palette = 'Set3')+
    theme(legend.position = 'bottom')

g4 <- ggplotGrob(p4)
g5 <- ggplotGrob(p5)
g6 <- ggplotGrob(p6)

grid.draw(rbind(g4,g5,g6, size='last'))
```

### Only Positive by Review Score Range - Reviews Containing Only Positive Words

```{r echo=FALSE}
zero_negative <- filter(full, Review_Total_Positive_Word_Counts > 0 & Review_Total_Negative_Word_Counts == 0)

zero_neg_rng = zero_negative %>%
    select(Review_Range, Total_Number_of_Reviews, Review_Total_Positive_Word_Counts, Hotel_Name) %>%
    # #Remove the 17 records without geo coordinates
    # filter(lat != 0 & lng != 0) %>%
    group_by(Review_Range) %>%
    summarise(Total_Words = sum(Review_Total_Positive_Word_Counts),
              Num_Reviews = n(),
              Avg_Words_Per_Review = format(Total_Words/Num_Reviews,digits = 4)
              )


# -- -- -- -- -- -- -- -- -- --     >      >      >     >
p7 <- ggplot(zero_neg_rng, aes(x=Review_Range,
                               y=Num_Reviews,
                               fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=zero_neg_rng$Num_Reviews,nudge_y = 0.5)+
    ggtitle(label="Reviews with Only Positive Words - Number of Reviews by Range of Score")+
    labs(xlab('Review Range'),ylab('Number of Reviews'))+
    scale_fill_brewer(palette = 'Pastel1')+
    theme(legend.position = 'off')

p8 <- ggplot(zero_neg_rng, aes(x=Review_Range,
                               y=Avg_Words_Per_Review,
                               fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=zero_neg_rng$Avg_Words_Per_Review,nudge_y = 0.2)+
    ggtitle(label="Reviews with Only Positive Words - Average Words per Review by Range of Score")+
    labs(xlab('Review Range'),ylab('Avg. Words per Review'))+
    scale_fill_brewer(palette = 'Pastel1')+
    theme(legend.position = 'off')


p9 <- ggplot(zero_neg_rng, aes(x=Review_Range,
                               y=Total_Words,
                               fill=Review_Range))+
    geom_bar(stat='identity', alpha=0.7)+
    geom_text(label=zero_neg_rng$Total_Words,nudge_y = 0.2)+
    ggtitle(label="Reviews with Only Positive Words - Number of Positive Words by Range of Score")+
    labs(xlab('Review Range'),ylab('Number of Positive Words'))+
    scale_fill_brewer(palette = 'Pastel1')+
    theme(legend.position = 'bottom')

g7 <- ggplotGrob(p7)
g8 <- ggplotGrob(p8)
g9 <- ggplotGrob(p9)

grid.draw(rbind(g7,g8,g9, size='last'))
```

### Country Stats

```{r country, echo=FALSE}
ggplot(data = country.stats, aes(x=reorder(Country,-Number_Hotels), y=Number_Hotels, fill=Country))+
    geom_bar(stat='identity', alpha=0.7) +
    geom_text(label=format(country.stats$Avg_Hotel_Review, digits = 2)) +
    labs(x='Country', y='Number of Hotels Reviewed') +
    ggtitle(label='Number of Hotels Reviewed & Avg. Score by Country') +
    scale_fill_brewer(palette='Pastel2')
```


### Leaflet Map

```{r leaflet, echo=FALSE}
points <- cbind(hotel.names$lng,hotel.names$lat)

leaflet() %>% 
    addProviderTiles('OpenStreetMap.Mapnik',
                     options = providerTileOptions(noWrap = TRUE)) %>%
    addMarkers(data = points,
               popup = paste0("<strong>Hotel: </strong>",
                              hotel.names$Hotel_Name,                 
                              "<br><strong>Address: </strong>", 
                              hotel.names$Hotel_Address, 
                              "<br><strong>Average Score: </strong>", 
                              hotel.names$Average_Score, 
                              "<br><strong>Number of Reviews: </strong>", 
                              hotel.names$Total_Number_of_Reviews,
                              "<br><strong>Percent Positive Review Words: </strong>",
                              hotel.names$Pos_Word_Rate),
               clusterOptions = markerClusterOptions())
```